/**
 * ============================================================
 * Personality Model (backend/models/Personality.js)
 * ============================================================
 * Phase 5 — Part A: AI Personality Snapshot
 *
 * Purpose:
 * Stores the user's answers to the 10 legacy questions and the
 * AI-synthesized personality summary, core traits, strengths,
 * legacy declaration, and personal quote generated by Gemini.
 *
 * Fields:
 * - userId: References the authenticated User
 * - answers: Array of question & answer pairs
 * - personalitySummary: 2-3 paragraph synthesized portrait
 * - traits: 5 core character traits
 * - strengths: 3 standout virtues / strengths
 * - legacy: Powerful sentence of how this person will be remembered
 * - quote: Meaningful fitting philosophical quote
 * - createdAt, updatedAt: Timestamps
 * ============================================================
 */

const mongoose = require('mongoose');

const personalitySchema = new mongoose.Schema(
  {
    // The authenticated user who owns this personality snapshot
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'A valid userId is required'],
      unique: true,
      index: true,
    },
    // The user's answers to the 10 reflection questions
    answers: [
      {
        question: { type: String, required: true },
        answer: { type: String, required: true },
      },
    ],
    // The 2-3 paragraph AI personality portrait
    personalitySummary: {
      type: String,
      required: [true, 'Personality summary is required'],
    },
    // 5 personality traits (e.g. Compassionate, Resilient, Visionary)
    traits: {
      type: [String],
      default: [],
    },
    // 3 core strengths
    strengths: {
      type: [String],
      default: [],
    },
    // One powerful sentence about their legacy
    legacy: {
      type: String,
      default: '',
    },
    // Meaningful quote
    quote: {
      type: String,
      default: '',
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Personality', personalitySchema);
